// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm5GaeecS4oDZZ0JtxG4G6RX8gOzRNhGk',
    appId: '1:345663521828:web:91da3cc2d503a77c9d84b1',
    messagingSenderId: '345663521828',
    projectId: 'xserver-2a8df',
    authDomain: 'xserver-2a8df.firebaseapp.com',
    storageBucket: 'xserver-2a8df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsgu2G52_Yib1Ipfx-63BBnisvh99wBQ0',
    appId: '1:345663521828:android:bda3bd2a53d651b59d84b1',
    messagingSenderId: '345663521828',
    projectId: 'xserver-2a8df',
    storageBucket: 'xserver-2a8df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGhvn1ExluxcZyM5HeoHKGNM8pt5y01eg',
    appId: '1:345663521828:ios:e2839136cf0974969d84b1',
    messagingSenderId: '345663521828',
    projectId: 'xserver-2a8df',
    storageBucket: 'xserver-2a8df.appspot.com',
    iosBundleId: 'app.com.mm.xserver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGhvn1ExluxcZyM5HeoHKGNM8pt5y01eg',
    appId: '1:345663521828:ios:e2839136cf0974969d84b1',
    messagingSenderId: '345663521828',
    projectId: 'xserver-2a8df',
    storageBucket: 'xserver-2a8df.appspot.com',
    iosBundleId: 'app.com.mm.xserver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm5GaeecS4oDZZ0JtxG4G6RX8gOzRNhGk',
    appId: '1:345663521828:web:bc69a703455158ef9d84b1',
    messagingSenderId: '345663521828',
    projectId: 'xserver-2a8df',
    authDomain: 'xserver-2a8df.firebaseapp.com',
    storageBucket: 'xserver-2a8df.appspot.com',
  );
}
